### ISSUE TITLE
CentOS 7: Missing spandsp >= 3.0

### ISSUE THREAD

**Issue by tcreek** [freeswitch/spandsp#12]
Did the following:

1) cloned
2) executed yum-prepare.sh
3) executed bootstrap.sh
4) make
5) make install
6) ldconfig

However, back in FreeSwitch, during configure, I am still getting: 

`checking for spandsp >= 3.0... configure: error: no usable spandsp; please install spandsp3 devel package or equivalent`

**Comment by mjerris** [comment]
the packages are in our repo.  please check again and confirm

**Comment by tcreek** [comment]
I am using this source, not the repo.

**Comment by mjerris** [comment]
conflim that the directory its installing the package config file to is in the PKG_CONFIG_PATH

**Comment by tcreek** [comment]
I just went ahead and used the FreeSwitch repo for now. I will look into your suggestion at a later time. Maybe there should be a better guide to make sure this is set up properly?

**Comment by mjerris** [comment]
it defaults to install to /usr/loca which is not going to be found in PKG_CONFIG_PATH by default. The packages install to /usr
