### ISSUE TITLE
Install Freesswitch on Ubuntu 20.04.5 

### ISSUE THREAD

**Issue by hrg92** [freeswitch/spandsp#45]
Hello

I am installing freeswitch on an ubuntu 20.04.5 server but when I run make to build freeswitch it gives me the following error

I have tried to install it in centOS 7 and it gives me the same error.

Could that be happening?

![image](https://user-images.githubusercontent.com/97411986/213762736-a2f95b89-b1cc-4c49-834b-4897fe8eb779.png)

**Comment by andywolk** [comment]
We do not support Ubuntu. On the other hand you can try downgrading to ffmpeg 4 or disable mod_av in `modules.conf` if you don't need mod_av.

**Comment by andywolk** [comment]
This is not a spandsp issue.
