### ISSUE TITLE
V.17 fixed point issues

### ISSUE THREAD

**Issue by lexxer3d** [freeswitch/spandsp#53]
Hi!

I've found the following issues while testing V.17 14400 TCF with fax_decode tool when compiled with fixed point support:

1. v17rx.c is missing SPANDSP_USE_FIXED_POINTx
2. int32 overflow happens for s->training_error, long training threshold (line 961) and training succeeded threshold (line 1139).

Suggested fix with TCF sample is attached.
[v17_fixedp.zip](https://github.com/freeswitch/spandsp/files/12015809/v17_fixedp.zip)

**Comment by coppice-git** [comment]
I have commited this change. I haven't really been keeping the fixed point stuff up to date, as nobody seemed to care about it. May I ask what platform you are using the fixed point code on? Do you have problems with the other modems? The last time I remember looking at the fixed point stuff I thought there were still multiple scaling issues in the modems.

**Comment by lexxer3d** [comment]
It's armv7l. Btw, even with the fix it doesn't work fine, so I switched to float point.
Tried two different modems.

**Comment by lexxer3d** [comment]
Fixed in commit 239bf2f6.
