### ISSUE TITLE
T.38 gw: V.17 call failing if far-end fails to train (FTT)

### ISSUE THREAD

**Issue by lexxer3d** [freeswitch/spandsp#54]
Hi!

When t38_gateway on sender side receives FTT, the subsequent TCF is sent to far-end as v17-14400-short-training not as v17-14400-long-training. Also we should switch to V.21 since as per Figure 5-2a/T.30, (TSI)DCS should be repeated as well.

Spandsp log and suggested fix is attached.
[ftt.zip](https://github.com/freeswitch/spandsp/files/12016225/ftt.zip)

**Comment by coppice-git** [comment]
I just committed the a change, more or less as suggested. Its weird that didn't show up before. I'll have to put some more tests in the test scripts to test the fix more thoroughly, but its clearly a basically correct thing to do.

**Comment by lexxer3d** [comment]
Fixed by commit 227b3126.
