### ISSUE TITLE
Segfault on writing tiff

### ISSUE THREAD

**Issue by upcFrost** [freeswitch/spandsp#72]
Hi,

I've encountered a segfault when trying to use spandsp to receive a T.30 on FreeSwitch.
SpanDSP version: 0d2e6ac65e0e8f53d652665a743015a88bf048d4 (from the FreeSwitch Debian 11 repo).
I've checked master and i don't think this part was changed since that commit.

Backtrace: [fs_spandsp_backtrace.log](https://github.com/freeswitch/spandsp/files/14027499/fs_spandsp_backtrace.log)

Could you please take a look?

Best regards,
Petr

**Comment by briankwest** [comment]
You'll need to update to the latest SpanDSP from https://github.com/freeswitch/spandsp
